let expenses=JSON.parse(localStorage.getItem('expenses'))||[];
let wallet=JSON.parse(localStorage.getItem('wallet'))||[];
let repayments=JSON.parse(localStorage.getItem('repayments'))||[];
let budget=Number(localStorage.getItem('vacationBudget'))||0;
const tripStart=new Date(2026,8,17),tripEnd=new Date(2026,9,20);
const money=n=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(Math.round(Number(n)||0));
const dateValue=d=>{const x=new Date(d);return new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const todayValue=dateValue(new Date());
function saveData(){localStorage.setItem('expenses',JSON.stringify(expenses));localStorage.setItem('wallet',JSON.stringify(wallet));localStorage.setItem('repayments',JSON.stringify(repayments));localStorage.setItem('vacationBudget',String(budget));}
function addMoney(){const amount=Number(moneyAmount.value);if(!amount||amount<0)return alert('Enter a valid amount');wallet.unshift({id:Date.now(),amount,source:moneySource.value,lender:lender.value.trim(),note:moneyNote.value.trim(),date:moneyDate.value?new Date(moneyDate.value+'T12:00:00').toISOString():new Date().toISOString()});saveData();moneyAmount.value='';lender.value='';moneyNote.value='';moneyDate.value=todayValue;render();alert('Money added successfully');}
function addExpense(){const amount=Number(document.getElementById('amount').value);if(!amount||amount<0)return alert('Enter a valid amount');expenses.unshift({id:Date.now(),amount,category:category.value,payment:payment.value,note:note.value.trim(),date:expenseDate.value?new Date(expenseDate.value+'T12:00:00').toISOString():new Date().toISOString()});saveData();document.getElementById('amount').value='';note.value='';expenseDate.value=todayValue;render();alert('Expense added successfully');}
function addRepayment(){const amount=Number(repayAmount.value);if(!amount||amount<0)return alert('Enter a valid amount');const borrowed=wallet.filter(x=>x.source==='Borrowed').reduce((a,b)=>a+b.amount,0);const repaid=repayments.reduce((a,b)=>a+b.amount,0);if(amount>borrowed-repaid)return alert('Repayment is higher than your borrowed balance.');repayments.unshift({id:Date.now(),amount,person:repayPerson.value.trim(),note:repayNote.value.trim(),date:repayDate.value?new Date(repayDate.value+'T12:00:00').toISOString():new Date().toISOString()});saveData();repayAmount.value='';repayPerson.value='';repayNote.value='';repayDate.value=todayValue;render();alert('Repayment recorded');}
function totals(){const added=wallet.reduce((a,b)=>a+b.amount,0);const spent=expenses.reduce((a,b)=>a+b.amount,0);const repaid=repayments.reduce((a,b)=>a+b.amount,0);return{added,spent,repaid,outflow:spent+repaid,remaining:added-spent-repaid,borrowed:wallet.filter(x=>x.source==='Borrowed').reduce((a,b)=>a+b.amount,0)-repaid};}
function tripInfo(){const now=new Date();const total=Math.round((tripEnd-tripStart)/86400000)+1;if(now<tripStart)return{status:'before',daysUntil:Math.ceil((tripStart-now)/86400000),remaining:total};if(now>tripEnd)return{status:'after',day:total,remaining:0};const day=Math.floor((now-tripStart)/86400000)+1;return{status:'during',day,remaining:total-day};}
function updateTripDay(){const t=tripInfo();if(t.status==='before')tripDay.textContent='Trip starts in '+t.daysUntil+' day'+(t.daysUntil===1?'':'s');else if(t.status==='after')tripDay.textContent='Vacation completed • 34 days';else tripDay.textContent='Day '+t.day+' / 34 • '+t.remaining+' days remaining';daysRemaining.textContent=t.status==='before'?34:t.remaining;}
function updateDashboard(){const t=totals(),info=tripInfo();moneyAvailable.textContent='₹'+money(t.added);totalSpent.textContent='₹'+money(t.outflow);remainingMoney.textContent='₹'+money(t.remaining);borrowedBalance.textContent='₹'+money(Math.max(0,t.borrowed));
const used=budget>0?t.outflow:0;const pct=budget>0?Math.min(100,(used/budget)*100):0;budgetAmount.textContent='₹'+money(budget);budgetUsed.textContent=budget>0?'₹'+money(used)+' used':'Set a budget to track progress';budgetPercent.textContent=Math.round(pct)+'%';budgetProgress.style.width=pct+'%';
const today=dateValue(new Date());const todayTotal=expenses.filter(x=>dateValue(x.date)===today).reduce((a,b)=>a+b.amount,0)+repayments.filter(x=>dateValue(x.date)===today).reduce((a,b)=>a+b.amount,0);todaySpent.textContent='₹'+money(todayTotal);
const days=Math.max(1,info.status==='during'?info.remaining+1:info.status==='before'?34:1);const base=budget>0?Math.max(0,budget-t.outflow):Math.max(0,t.remaining);dailyLimit.textContent='₹'+money(base/days);}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function showHistory(){const box=document.getElementById('history');const all=[...wallet.map(x=>({...x,type:'money'})),...expenses.map(x=>({...x,type:'expense'})),...repayments.map(x=>({...x,type:'repayment'}))].sort((a,b)=>b.id-a.id);document.getElementById('historyCount').textContent=all.length+' transaction'+(all.length===1?'':'s');box.innerHTML=all.length?'':'<div class="empty">No transactions yet.<br>Add your first amount or expense.</div>';all.forEach(x=>{let title,meta;if(x.type==='money'){title='💰 '+esc(x.source);meta=x.source==='Borrowed'&&x.lender?'From '+esc(x.lender):''}else if(x.type==='expense'){title='💸 '+esc(x.category);meta=esc(x.payment)}else{title='↩️ Repayment';meta=x.person?'To '+esc(x.person):''}box.insertAdjacentHTML('beforeend',`<div class="item"><div class="item-main"><div><b>${title}</b><small>${meta}</small><small>${esc(x.note||'')}</small><small>📅 ${new Date(x.date).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</small></div><strong>₹${money(x.amount)}</strong></div><div class="item-actions"><button onclick="editTransaction(${x.id},'${x.type}')">Edit</button><button class="delete-btn" onclick="deleteTransaction(${x.id},'${x.type}')">Delete</button></div></div>`);});}
function editTransaction(id,type){let list=type==='money'?wallet:type==='expense'?expenses:repayments;const x=list.find(a=>a.id===id);if(!x)return;const amount=prompt('Amount ₹',x.amount);if(amount===null)return;const n=Number(amount);if(!n||n<0)return alert('Invalid amount');const noteText=prompt('Note / description',x.note||'');x.amount=n;if(noteText!==null)x.note=noteText.trim();if(type==='money'&&x.source==='Borrowed'){const p=prompt('Borrowed from',x.lender||'');if(p!==null)x.lender=p.trim();}if(type==='repayment'){const p=prompt('Person / lender',x.person||'');if(p!==null)x.person=p.trim();}saveData();render();}
function deleteTransaction(id,type){if(!confirm('Delete this transaction?'))return;let key=type==='money'?'wallet':type==='expense'?'expenses':'repayments';window[key]=window[key].filter(x=>x.id!==id);saveData();render();}
function updateReports(){const t=totals(),info=tripInfo();const daysUsed=info.status==='before'?0:Math.min(34,info.status==='after'?34:info.day);const avg=daysUsed?Math.round(t.outflow/daysUsed):0;document.getElementById('reportSummary').innerHTML=`<div class="report-grid"><div><span>Total spent</span><b>₹${money(t.outflow)}</b></div><div><span>Daily average</span><b>₹${money(avg)}</b></div><div><span>Transactions</span><b>${expenses.length+repayments.length}</b></div><div><span>Borrowed balance</span><b>₹${money(Math.max(0,t.borrowed))}</b></div></div>`;
const groups={};expenses.forEach(x=>groups[x.category]=(groups[x.category]||0)+x.amount);const rows=Object.entries(groups).sort((a,b)=>b[1]-a[1]);const max=rows[0]?.[1]||1;document.getElementById('categoryReport').innerHTML=rows.length?rows.map(([name,val])=>`<div class="bar-row"><div><span>${esc(name)}</span><b>₹${money(val)}</b></div><i><em style="width:${Math.max(4,(val/max)*100)}%"></em></i></div>`).join(''):'<div class="empty">Category spending will appear here after you add expenses.</div>';}
function saveBudget(){const n=Number(budgetInput.value);if(n<0||Number.isNaN(n))return alert('Enter a valid budget');budget=n;saveData();render();alert('Vacation budget saved');}
function exportData(){const data={version:3,budget,wallet,expenses,repayments};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='Kerala_Vacation_Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=x=>{try{const d=JSON.parse(x.target.result);if(!Array.isArray(d.wallet)||!Array.isArray(d.expenses))throw new Error();wallet=d.wallet;expenses=d.expenses;repayments=Array.isArray(d.repayments)?d.repayments:[];budget=Number(d.budget)||0;saveData();render();alert('Backup restored successfully');}catch(err){alert('Invalid backup file.')}};r.readAsText(f);e.target.value='';}
function clearData(){if(confirm('Delete all vacation data? This cannot be undone.')){wallet=[];expenses=[];repayments=[];budget=0;saveData();render();}}
function showTab(id){document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='settings')budgetInput.value=budget||'';window.scrollTo({top:0,behavior:'smooth'});}
function render(){updateDashboard();updateTripDay();showHistory();updateReports();if(document.getElementById('budgetInput'))budgetInput.value=budget||'';}
[moneyDate,expenseDate,repayDate].forEach(x=>x.value=todayValue);
render();