const defaultData={expenses:[],receivables:[],payables:[],cards:[],accounts:[],goals:[],investments:[],history:[],pin:null};
let financeData=JSON.parse(localStorage.getItem('abdullaFinance'))||defaultData;
function saveData(){localStorage.setItem('abdullaFinance',JSON.stringify(financeData));updateDashboard();renderLists();}
function addHistory(type,data){financeData.history.unshift({type,...data,date:new Date().toISOString()});}
function addTransaction(type,name,amount){financeData[type].push({id:Date.now(),name,amount:Number(amount)});addHistory(type,{name,amount:Number(amount)});saveData();}
function addReceive(){if(receiveName.value&&receiveAmount.value)addTransaction('receivables',receiveName.value,receiveAmount.value);}
function addPay(){if(payName.value&&payAmount.value)addTransaction('payables',payName.value,payAmount.value);}
function addCard(){if(cardName.value&&cardOutstanding.value){financeData.cards.push({id:Date.now(),name:cardName.value,amount:Number(cardOutstanding.value)});saveData();}}
function addSaving(){if(savingName.value&&savingAmount.value){financeData.goals.push({name:savingName.value,target:Number(savingTarget.value||0),saved:Number(savingAmount.value)});saveData();}}
function addInvestment(){if(investmentName.value&&investmentAmount.value){financeData.investments.push({name:investmentName.value,type:investmentType.value||'Other',amount:Number(investmentAmount.value),value:Number(investmentValue.value||investmentAmount.value)});saveData();}}
function totals(){return {receive:financeData.receivables.reduce((a,b)=>a+b.amount,0),pay:financeData.payables.reduce((a,b)=>a+b.amount,0),cards:financeData.cards.reduce((a,b)=>a+b.amount,0),savings:financeData.goals.reduce((a,b)=>a+b.saved,0),investments:financeData.investments.reduce((a,b)=>a+b.value,0)}}
function updateDashboard(){let t=totals();if(cash)cash.innerHTML=t.receive-t.pay+' QAR';if(receive)receive.innerHTML=t.receive+' QAR';if(pay)pay.innerHTML=t.pay+' QAR';if(cards)cards.innerHTML=t.cards+' QAR';if(savingsTotal)savingsTotal.innerHTML=t.savings+' QAR';if(investmentTotal)investmentTotal.innerHTML=t.investments+' QAR';}
function renderLists(){if(payList)payList.innerHTML=financeData.payables.map(x=>`<p>🔴 ${x.name}: ${x.amount} QAR</p>`).join('');if(cardList)cardList.innerHTML=financeData.cards.map(x=>`<p>💳 ${x.name}: ${x.amount} QAR</p>`).join('');if(savingList)savingList.innerHTML=financeData.goals.map(x=>`<p>💰 ${x.name}: ${x.saved}/${x.target} QAR</p>`).join('');if(investmentList)investmentList.innerHTML=financeData.investments.map(x=>`<p>📈 ${x.name} (${x.type}): ${x.value} QAR</p>`).join('');}
function exportBackup(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(financeData)]));a.download='backup.json';a.click();}
window.onload=()=>{updateDashboard();renderLists();};