const defaultData={receivables:[],payables:[],cards:[],goals:[],investments:[],history:[]};
let financeData=JSON.parse(localStorage.getItem('abdullaFinance'))||defaultData;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem('abdullaFinance',JSON.stringify(financeData));update();render();}
function addHistory(type,item){financeData.history.unshift({type,...item,date:new Date().toLocaleDateString()});}
function addPay(){let x={name:$('payName').value,amount:+$('payAmount').value};if(x.name&&x.amount){financeData.payables.push(x);addHistory('Pay',x);save();}}
function addReceive(){let x={name:$('receiveName').value,amount:+$('receiveAmount').value};if(x.name&&x.amount){financeData.receivables.push(x);addHistory('Receive',x);save();}}
function addCard(){if($('cardName').value){financeData.cards.push({name:$('cardName').value,amount:+$('cardOutstanding').value||0});save();}}
function addSaving(){if($('savingName').value){financeData.goals.push({name:$('savingName').value,target:+$('savingTarget').value||0,saved:+$('savingAmount').value||0});save();}}
function addInvestment(){if($('investmentName').value){financeData.investments.push({name:$('investmentName').value,value:+$('investmentValue').value||0});save();}}
function update(){let r=financeData.receivables.reduce((a,b)=>a+b.amount,0),p=financeData.payables.reduce((a,b)=>a+b.amount,0),c=financeData.cards.reduce((a,b)=>a+b.amount,0),s=financeData.goals.reduce((a,b)=>a+b.saved,0),i=financeData.investments.reduce((a,b)=>a+b.value,0);$('cash').innerHTML=(r-p)+' QAR';$('receive').innerHTML=r+' QAR';$('pay').innerHTML=p+' QAR';$('cards').innerHTML=c+' QAR';$('savingsTotal').innerHTML=s+' QAR';$('investmentTotal').innerHTML=i+' QAR';}
function render(){if($('receiveList'))$('receiveList').innerHTML=financeData.receivables.map(x=>`<p>🟢 ${x.name}: ${x.amount} QAR</p>`).join('');if($('payList'))$('payList').innerHTML=financeData.payables.map(x=>`<p>🔴 ${x.name}: ${x.amount} QAR</p>`).join('');if($('cardList'))$('cardList').innerHTML=financeData.cards.map(x=>`<p>💳 ${x.name}: ${x.amount} QAR</p>`).join('');if($('savingList'))$('savingList').innerHTML=financeData.goals.map(x=>`<p>💰 ${x.name}: ${x.saved}/${x.target}</p>`).join('');if($('investmentList'))$('investmentList').innerHTML=financeData.investments.map(x=>`<p>📈 ${x.name}: ${x.value} QAR</p>`).join('');if($('historyList'))$('historyList').innerHTML=financeData.history.map(x=>`<p>${x.type}: ${x.name||''} ${x.amount||''}</p>`).join('');}
window.onload=()=>{update();render();};