const KEY='itdesk-v2-assets';
const cfg=window.ITDESK_SUPABASE||{};
const cloudReady=Boolean(cfg.url&&cfg.anonKey&&window.supabase);
const db=cloudReady?window.supabase.createClient(cfg.url,cfg.anonKey):null;
const state={assets:JSON.parse(localStorage.getItem(KEY)||'[]'),session:null};
const $=s=>document.querySelector(s),content=$('#content'),modal=$('#modal'),authScreen=$('#authScreen');
let authMode='login';
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(state.assets))}
function esc(v=''){return String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[c]))}
function daysTo(d){if(!d)return null;return Math.ceil((new Date(d)-new Date())/86400000)}
function setSync(text,good=false){$('#syncStatus').textContent=text;$('#userStatus').textContent=text;$('#userStatus').classList.toggle('good',good)}
function showAuth(){authScreen.classList.remove('hidden');setSync('Sign in required');$('#quickAdd').disabled=true;$('#signOut').style.display='none';$('#userEmail').textContent=''}
function hideAuth(){authScreen.classList.add('hidden');$('#quickAdd').disabled=false;$('#signOut').style.display='inline-flex';$('#userEmail').textContent=state.session?.user?.email||''}
function setAuthMessage(text,error=false){const el=$('#authMessage');el.textContent=text;el.classList.toggle('error',error)}
function switchAuthMode(){authMode=authMode==='login'?'signup':'login';$('#authTitle').textContent=authMode==='login'?'Sign in to ITDesk':'Create your ITDesk account';$('#authHint').textContent=authMode==='login'?'Your PC and iPhone will use the same cloud workspace.':'Use the same email and password on your PC and iPhone.';$('#authSubmit').textContent=authMode==='login'?'Sign in':'Create account';$('#authSwitch').textContent=authMode==='login'?'New here? Create an account':'Already have an account? Sign in';setAuthMessage('')}
async function loadAssets(){
  if(!db||!state.session){return}
  setSync('Syncing…');
  try{const {data,error}=await db.from('assets').select('*').order('created_at',{ascending:false});if(error)throw error;state.assets=(data||[]).map(a=>({...a,assetId:a.asset_id}));saveLocal();setSync('Cloud synced',true);dashboard()}
  catch(e){console.error(e);setSync('Cloud error');alert('Cloud database is not ready yet. Run itdesk/supabase/schema.sql in Supabase SQL Editor, then refresh.')}
}
async function createAsset(asset){
  if(!state.session){showAuth();return}
  state.assets.unshift(asset);saveLocal();
  const row={id:asset.id,user_id:state.session.user.id,name:asset.name,type:asset.type,model:asset.model||'',asset_id:asset.assetId||'',serial:asset.serial||'',ip:asset.ip||'',location:asset.location||'',warranty:asset.warranty||null,notes:asset.notes||''};
  const {error}=await db.from('assets').insert(row);
  if(error){console.error(error);state.assets=state.assets.filter(a=>a.id!==asset.id);saveLocal();setSync('Cloud save failed');alert(error.message)}else setSync('Cloud synced',true)
}
async function removeAsset(id){if(!confirm('Delete this asset?'))return;state.assets=state.assets.filter(a=>a.id!==id);saveLocal();if(db&&state.session){const {error}=await db.from('assets').delete().eq('id',id);if(error){console.error(error);setSync('Cloud delete failed');alert(error.message)}}renderRows();dashboard()}
function dashboard(){const exp=state.assets.filter(a=>{const x=daysTo(a.warranty);return x!==null&&x<=60&&x>=0});content.innerHTML=`<div class="cards"><div class="card"><div class="label">TOTAL ASSETS</div><div class="value">${state.assets.length}</div><div class="sub">Tracked devices</div></div><div class="card"><div class="label">NETWORK</div><div class="value">${state.assets.filter(a=>['Firewall','Switch','Access Point'].includes(a.type)).length}</div><div class="sub">Core infrastructure</div></div><div class="card"><div class="label">SERVERS</div><div class="value">${state.assets.filter(a=>a.type==='Server').length}</div><div class="sub">Compute assets</div></div><div class="card"><div class="label">EXPIRING SOON</div><div class="value ${exp.length?'danger':''}">${exp.length}</div><div class="sub">Warranty within 60 days</div></div></div><div class="panel"><div class="panel-head"><h2>Recent assets</h2><button class="ghost" onclick="showPage('assets')">View all</button></div>${state.assets.length?`<div class="list">${state.assets.slice(0,5).map(a=>`<div class="row"><div><strong>${esc(a.name)}</strong><div class="muted">${esc(a.type)} · ${esc(a.location||'No location')}</div></div><span class="pill">${esc(a.assetId||'No ID')}</span></div>`).join('')}</div>`:'<div class="empty">No assets yet. Add your first device to start the IT inventory.</div>'}</div>`}
function assets(){content.innerHTML=`<div class="panel"><div class="panel-head"><h2>Asset inventory</h2><div class="toolbar"><input class="search" id="assetSearch" placeholder="Search name, asset ID, IP, serial..."></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Asset</th><th>Type</th><th>Location</th><th>IP</th><th>Warranty</th><th></th></tr></thead><tbody id="assetRows"></tbody></table></div></div>`;renderRows();$('#assetSearch').oninput=renderRows}
function renderRows(){const q=($('#assetSearch')?.value||'').toLowerCase();const rows=state.assets.filter(a=>Object.values(a).join(' ').toLowerCase().includes(q));$('#assetRows').innerHTML=rows.length?rows.map(a=>`<tr><td><strong>${esc(a.name)}</strong><div class="muted">${esc(a.assetId||'')} ${a.model?'· '+esc(a.model):''}</div></td><td><span class="pill">${esc(a.type)}</span></td><td>${esc(a.location||'—')}</td><td>${esc(a.ip||'—')}</td><td>${a.warranty?esc(a.warranty):'—'}</td><td><button class="ghost" onclick="removeAsset('${a.id}')">Delete</button></td></tr>`).join(''):`<tr><td colspan="6"><div class="empty">No matching assets.</div></td></tr>`}
function simplePage(title,desc,items){content.innerHTML=`<div class="panel"><div class="panel-head"><div><h2>${title}</h2><div class="muted">${desc}</div></div></div><div class="empty">${items||'This module is prepared for the next build.'}</div></div>`}
function network(){const n=state.assets.filter(a=>['Firewall','Switch','Access Point'].includes(a.type));simplePage('Network inventory','Firewall, switches and access points',n.length?`<div class="list">${n.map(a=>`<div class="row"><div><strong>${esc(a.name)}</strong><div class="muted">${esc(a.type)} · ${esc(a.location||'')}</div></div><span>${esc(a.ip||'No IP')}</span></div>`).join('')}</div>`:null)}
function maintenance(){simplePage('Maintenance','Service schedules and maintenance history','<strong>Next module</strong><br><span class="muted">Tasks, due dates, technician, status and service history.</span>')}
function licenses(){simplePage('Licenses & Contracts','Track renewals, AMCs and vendor contracts','<strong>Next module</strong><br><span class="muted">Expiry dates, vendors, renewal reminders and cost tracking.</span>')}
function incidents(){simplePage('Incidents','Track IT problems from open to resolved','<strong>Next module</strong><br><span class="muted">Priority, assignment, status, resolution and history.</span>')}
function showPage(page){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#pageTitle').textContent={dashboard:'Dashboard',assets:'Assets',network:'Network',maintenance:'Maintenance',licenses:'Licenses & Contracts',incidents:'Incidents'}[page];({dashboard,assets,network,maintenance,licenses,incidents}[page])();document.querySelector('.sidebar').classList.remove('open')}
function openModal(){if(!state.session){showAuth();return}modal.classList.remove('hidden');$('#assetForm').reset()}function closeModal(){modal.classList.add('hidden')}
async function handleAuth(e){e.preventDefault();if(!db){setAuthMessage('Cloud configuration is missing.',true);return}const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(password.length<6){setAuthMessage('Password must be at least 6 characters.',true);return}$('#authSubmit').disabled=true;setAuthMessage('Working…');try{if(authMode==='login'){const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;setAuthMessage('Signed in.')}else{const {data,error}=await db.auth.signUp({email,password});if(error)throw error;if(!data.session)setAuthMessage('Account created. Check your email to confirm it, then sign in.');else setAuthMessage('Account created.')}}catch(err){setAuthMessage(err.message||'Authentication failed.',true)}finally{$('#authSubmit').disabled=false}}
async function handleSession(session){state.session=session;if(session){hideAuth();setSync('Signed in');await loadAssets();showPage('dashboard')}else{showAuth();showPage('dashboard')}}
$('#nav').onclick=e=>{const b=e.target.closest('button');if(b)showPage(b.dataset.page)};$('#quickAdd').onclick=openModal;$('#closeModal').onclick=closeModal;$('#cancelModal').onclick=closeModal;$('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');$('#assetForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await createAsset({id:crypto.randomUUID(),name:f.get('name'),type:f.get('type'),model:f.get('model'),assetId:f.get('assetId'),serial:f.get('serial'),ip:f.get('ip'),location:f.get('location'),warranty:f.get('warranty'),notes:f.get('notes')});closeModal();showPage('assets')};$('#authForm').onsubmit=handleAuth;$('#authSwitch').onclick=e=>{e.preventDefault();switchAuthMode()};$('#signOut').onclick=async()=>{if(db)await db.auth.signOut()};window.removeAsset=removeAsset;window.showPage=showPage;
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
if(db){db.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>handleSession(session),0)});db.auth.getSession().then(({data})=>handleSession(data.session))}else{showAuth();setAuthMessage('Supabase configuration is missing.',true)}
